using ProductInfoService.Business.Interfaces;
using ProductInfoService.Business.Services;
using ProductInfoService.Data.Interfaces;
using ProductInfoService.Data.Repositories;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();

//Generated by ChatGPT o1-preview
builder.Services.AddScoped<IProductService, ProductService>();
builder.Services.AddScoped<IProductRepository, ProductRepository>();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
