using Microsoft.AspNetCore.Mvc;
using ProductInfoService.Business.Interfaces;

namespace ProductInfoService.API.Controllers;

//Generated by ChatGPT o1-preview 
[ApiController]
[Route("api/[controller]")]
public class ProductController : ControllerBase
{
    private readonly IProductService _productService;

    public ProductController(IProductService productService)
    {
        _productService = productService;
    }

    [HttpGet("{id}")]
    public IActionResult GetProductById(int id)
    {
        var product = _productService.GetProductById(id);
        if (product == null)
        {
            return NotFound();
        }
        return Ok(product);
    }
}

